import type { Metadata } from "next";
import { Arimo } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import ScrollToTop from "@/components/ui/ScrollToTop";

const arimo = Arimo({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={arimo.className}>
        <Navbar />
        {children}
        <ScrollToTop />
        <Footer companyName="LOGO" />
      </body>
    </html>
  );
}
